### ISSUE TITLE
Pick a coding standard and linter

### ISSUE THREAD

**Issue by NripeshManandhar** [solarcaratuva/TemplateCode#13]
Coding Standards:
- [ ] MISRA C++
- [ ] JSF C++
- [ ] AUTOSAR C++

Linters:
- [ ] Splint
- [ ] cppcheck
- [ ] clang-format

After picking a coding standard, set up a linter and integrate it with CircleCI

**Comment by willzhang05** [comment]
[https://www.misra.org.uk/LinkClick.aspx?fileticket=n7HwIG-0JYk%3D&tabid=59](url)

Looks like MISRA + AUTOSAR are going to be merged standards as of 2019. JSF is more for air vehicles, so this is a pretty easy choice to go with MISRA + AUTOSAR, but the merged standards aren't published yet. AUTOSAR allows for use of C++14 features, so we should go with AUTOSAR for the time being before the combined standard is published.

**Comment by willzhang05** [comment]
Out of date: [https://github.com/rettichschnidi/clang-tidy-misra](url)
Could be good [https://github.com/facebook/infer](url)
I like [https://clang.llvm.org/extra/clang-tidy/](url)
